#!/bin/sh
echo
for i in AA AE AH AO AW AY B CH D DH EH ER EY F G HH IH IY JH K L M N NG OW OY P R S SH T TH UH UW V W Y Z ZH
do
      echo -n $i $j: 
      perl fsearch.pl "^c(.)?(\s)($i).(\s)c(.)?(\s)[1..9]"

echo
done
